Ccp 2409 add portals
shopgate/ext-youtube-pdp pull request #3
Opened 2021-04-30 09:32 UTC by Phmank

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix
- [X] New feature
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I updated the CHANGELOG.md

2021-04-30 12:51 UTC, Carsten89 requested changes

2021-04-30 12:51 UTC, Carsten89 commented on extension-config.json
> +        "type": "json",
```suggestion
        "type": "text",
```

2021-04-30 12:51 UTC, Carsten89 commented on frontend/helpers/getConfig.js
> +
please remove this file. its not needed. you can access the config directly without the helper fn here

2021-04-30 12:51 UTC, Carsten89 commented on frontend/helpers/getConfig.spec.js
> +
this file should also be removed.

2021-04-30 12:53 UTC, Phmank commented on extension-config.json
> +        "type": "json",
Done

2021-05-03 06:18 UTC, Phmank commented on frontend/helpers/getConfig.js
> +
Done

2021-05-03 06:18 UTC, Phmank commented on frontend/helpers/getConfig.spec.js
> +
Done

2021-05-03 11:15 UTC, Carsten89 approved these changes

2021-05-03 11:25 UTC, merged